CREATE   VIEW dbo.vw_hotel_bookings_clean AS
SELECT
    hotel,
    TRY_CAST(is_canceled AS int) AS is_canceled,
    TRY_CAST(lead_time AS int) AS lead_time,
    TRY_CAST(arrival_date_year AS int) AS arrival_year,
    arrival_date_month AS arrival_month,
    TRY_CAST(arrival_date_week_number AS int) AS arrival_week_number,
    TRY_CAST(arrival_date_day_of_month AS int) AS arrival_day,
    TRY_CAST(stays_in_weekend_nights AS int) AS weekend_nights,
    TRY_CAST(stays_in_week_nights AS int) AS week_nights,
    TRY_CAST(stays_in_weekend_nights AS int) + TRY_CAST(stays_in_week_nights AS int) AS total_nights,
    TRY_CAST(adults AS int) AS adults,
    TRY_CAST(children AS float) AS children,
    TRY_CAST(babies AS int) AS babies,
    TRY_CAST(adults AS int) + ISNULL(TRY_CAST(children AS int), 0) + TRY_CAST(babies AS int) AS total_guests,
    meal,
    country,
    market_segment,
    distribution_channel,
    TRY_CAST(is_repeated_guest AS int) AS is_repeated_guest,
    TRY_CAST(previous_cancellations AS int) AS previous_cancellations,
    TRY_CAST(previous_bookings_not_canceled AS int) AS previous_bookings_not_canceled,
    reserved_room_type,
    assigned_room_type,
    TRY_CAST(booking_changes AS int) AS booking_changes,
    deposit_type,
    TRY_CAST(agent AS int) AS agent,
    TRY_CAST(company AS int) AS company,
    TRY_CAST(days_in_waiting_list AS int) AS days_in_waiting_list,
    customer_type,
    TRY_CAST(adr AS decimal(10,2)) AS adr,
    TRY_CAST(required_car_parking_spaces AS int) AS required_car_parking_spaces,
    TRY_CAST(total_of_special_requests AS int) AS total_special_requests,
    reservation_status,
    TRY_CAST(reservation_status_date AS date) AS reservation_status_date,
    TRY_CAST(stays_in_weekend_nights AS int) + TRY_CAST(stays_in_week_nights AS int) * TRY_CAST(adr AS decimal(10,2)) AS estimated_revenue
FROM dbo.hotel_bookings;